In [0]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
%matplotlib inline

In [0]:
data=datasets.load_diabetes()

In [6]:
data.keys()

dict_keys(['data', 'target', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

In [0]:
x=data.data
y=data.target


In [0]:
df=pd.DataFrame(data=data.data, columns=data.feature_names)
df['target']=y
df.head()

dx=df.drop('target', axis=1)
dy=df['target']

In [0]:
X_train,X_test,y_train,y_test=train_test_split(dx,dy, test_size=0.3 , random_state=42)

In [0]:
model= RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train,y_train)
predict=model.predict(X_test)


In [15]:
np.sqrt(metrics.mean_squared_error(y_test,predict))

53.505825893179875

In [0]:
#CLASSIFIER

In [0]:
data1=datasets.load_digits()


In [19]:
data1.keys()

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

In [22]:
data1.images

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

In [0]:
x=data1.data
y=data1.target

In [24]:
x.shape

(1797, 64)

In [25]:
y.shape

(1797,)

In [0]:
X_train,X_test,y_train,y_test=train_test_split(x,y, test_size=0.3 , random_state=42)

In [0]:
model=RandomForestClassifier(n_estimators=100, random_state=42)

In [0]:
model.fit(X_train,y_train)
predict=model.predict(X_test)

In [30]:
print("Accuracy:", metrics.accuracy_score(y_test,predict))
print("matrix:", metrics.confusion_matrix(y_test,predict))

Accuracy: 0.975925925925926
matrix: [[52  0  0  0  1  0  0  0  0  0]
 [ 0 50  0  0  0  0  0  0  0  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  0 52  0  0  0  0  2  0]
 [ 0  0  0  0 60  0  0  0  0  0]
 [ 0  0  0  0  1 63  1  0  0  1]
 [ 0  0  0  0  0  1 52  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  1]
 [ 0  2  0  0  0  0  0  0 41  0]
 [ 0  0  0  1  0  1  0  1  0 56]]
